DROP TABLE if EXISTS address_ CASCADE;
DROP TABLE if EXISTS users CASCADE;
-- DROP TABLE if EXISTS orders CASCADE;
DROP TABLE if EXISTS items CASCADE;
DROP TABLE if EXISTS cart_item CASCADE;
DROP TABLE if EXISTS user_to_cart CASCADE;
DROP TABLE if EXISTS user_to_address CASCADE;